name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Add your desired steps here
      - name: Run a script
        run: |
          git config user.email "prateekshettybdmi@gmail.com"
          git config user.name "prateeks007"

          npm install expo-cli --save-dev

          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GHPAT }}
