name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Add your desired steps here
      - name: Run a script
        run: |
          git config user.email "prateekshettybdmi@gmail.com"
          git config user.name "Prateek"

          git config --get remote.origin.url

          git config remote.origin.url "https://${{ secrets.GH_TOKEN }}@github.com/Portfolio

          git config --get remote.origin.url




          npm install expo-cli --save-dev

          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GHPAT }}
